author: ryosan-470
baseURL: https://ryosan-470.github.io/
defaultContentLanguage: en
enableGitInfo: true # Ref: https://gohugo.io/variables/git/
googleAnalytics: UA-80017772-3
hasCJKLanguage: true
pagenate: 5
permalinks:
  posts: /posts/:year/:month/:day/:filename
publishDir: docs
theme: beautifulhugo
title: ryosan-470 Blog

Params:
  mainSections:
    - posts
  commit: true
  rss: true
  comments: true
  readingTime: false
  wordCount: false
  socialShare: true
  showRelatedPosts: false
  useHLJS: true
  delayDisqus: true

Author:
  name: ryosan-470
  github: ryosan-470
  twitter: jtwp470

menu:
  main:
  - name: Blog
    url: posts
    weight: 3
  - name: Tags
    url: tags
    weight: 2
  - name: About
    url: about
    weight: 1
